#!/usr/bin/env bash

# source colors
source "$CONFIG_DIR/colors.sh"

# plugin and items dirs
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=37
  position=top
  blur_radius=30
  sticky=off
  padding_left=10
  padding_right=10
  color="$BAR_COLOR"
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color="$ITEM_COLOR"
  label.color="$ITEM_COLOR"
  background.color="$ITEM_BG_COLOR"
  background.corner_radius=5
  background.height=24
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
source "$ITEM_DIR/spaces.sh"

# -- Right Side Items --
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
